icons_format = "{icon}"
# [theme.solarized-dark]
# background = "#002b36"
# bad = "#dc322f"
# degraded = "#cb4b16"
# good = "#859900"
# warning = "#b58900"
# separator = "#586e75"
# idle = "#839496"
# info = "#2aa198"
# color_good = "#859900"
# color_bad = "#dc322f"
# color_degraded = "#cb4b16"
# color_neutral = "#839496"
#
[theme]
theme = "/home/geoff/dotfiles/config/i3status-rust/themes/nord-dark.toml"
# [theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"

[icons]
icons = "/home/geoff/dotfiles/config/i3status-rust/icons/awesome4.toml"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
# format = " $icon $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi)($mem_used_percents.eng(w:2)) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

# [[block]]
# block = "sound"
# [[block.click]]
# button = "left"
# cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
